// ╔══════════════════════════════════════════════════════════════════════════╗
// ║ Generated Regions                                                        ║
// ╚══════════════════════════════════════════════════════════════════════════╝
'use strict';

// ─────────────────────────────────────────────────────────────────────────────
// 1. CONSTANTS
// ─────────────────────────────────────────────────────────────────────────────

const BEGIN_PREFIX = '<!-- BEGIN GENERATED: AI-SYSTEM-SYNC ';
const END_PREFIX = '<!-- END GENERATED: AI-SYSTEM-SYNC ';
const MARKER_SUFFIX = ' -->';

// ─────────────────────────────────────────────────────────────────────────────
// 2. HELPERS
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Build the opening marker for a generated section.
 *
 * @param {string} section - Generated section name.
 * @returns {string} Opening marker text.
 */
function beginMarker(section) {
  return `${BEGIN_PREFIX}${section}${MARKER_SUFFIX}`;
}

/**
 * Build the closing marker for a generated section.
 *
 * @param {string} section - Generated section name.
 * @returns {string} Closing marker text.
 */
function endMarker(section) {
  return `${END_PREFIX}${section}${MARKER_SUFFIX}`;
}

/**
 * Locate a named generated region.
 *
 * @param {string} content - File content to inspect.
 * @param {string} section - Generated section name.
 * @returns {{beginIdx: number, bodyStart: number, endIdx: number, endOfEnd: number}|null}
 *   Region offsets or null when markers are incomplete.
 */
function findRegion(content, section) {
  const begin = beginMarker(section);
  const end = endMarker(section);
  const beginIdx = content.indexOf(begin);
  if (beginIdx === -1) return null;
  const bodyStart = beginIdx + begin.length;
  const endIdx = content.indexOf(end, bodyStart);
  if (endIdx === -1) return null;
  return { beginIdx, bodyStart, endIdx, endOfEnd: endIdx + end.length };
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. CORE LOGIC
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Render a full region block without changing caller-controlled body spacing.
 *
 * @param {string} section - Generated section name.
 * @param {string} body - Generated body text.
 * @returns {string} Marker-wrapped region text.
 */
function renderRegion(section, body) {
  return `${beginMarker(section)}\n${body}\n${endMarker(section)}`;
}

/**
 * Extract the body text of a named generated region.
 *
 * @param {string} content - File content to inspect.
 * @param {string} section - Generated section name.
 * @returns {string|null} Region body or null when the markers are absent.
 */
function extractRegion(content, section) {
  const loc = findRegion(content, section);
  if (!loc) return null;
  let body = content.slice(loc.bodyStart, loc.endIdx);
  if (body.startsWith('\n')) body = body.slice(1);
  if (body.endsWith('\n')) body = body.slice(0, -1);
  return body;
}

/**
 * Replace a named region body while preserving all surrounding content.
 *
 * @param {string} content - File content to update.
 * @param {string} section - Generated section name.
 * @param {string} newBody - Replacement body text.
 * @returns {string} Updated file content.
 * @throws {RegionNotFoundError} When the region markers are absent.
 */
function replaceRegion(content, section, newBody) {
  const loc = findRegion(content, section);
  if (!loc) {
    throw new RegionNotFoundError(
      `No "${section}" generated region markers found. Add ` +
        `"${beginMarker(section)}" / "${endMarker(section)}" to the file first.`
    );
  }
  const before = content.slice(0, loc.beginIdx);
  const after = content.slice(loc.endOfEnd);
  return `${before}${renderRegion(section, newBody)}${after}`;
}

/**
 * Compare a region body with the expected generated bytes.
 *
 * @param {string} content - File content to inspect.
 * @param {string} section - Generated section name.
 * @param {string} expectedBody - Expected generated body.
 * @returns {{scaffolded: boolean, matches: boolean}} Comparison result.
 */
function regionReproducesExactly(content, section, expectedBody) {
  const actual = extractRegion(content, section);
  if (actual === null) return { scaffolded: false, matches: false };
  return { scaffolded: true, matches: actual === expectedBody };
}

/**
 * List generated section names present in file content.
 *
 * @param {string} content - File content to inspect.
 * @returns {string[]} Generated section names in source order.
 */
function listSections(content) {
  const sections = [];
  const re = /<!-- BEGIN GENERATED: AI-SYSTEM-SYNC (.+?) -->/g;
  let match;
  while ((match = re.exec(content)) !== null) {
    sections.push(match[1]);
  }
  return sections;
}

/** Error raised when a generated region cannot be located. */
class RegionNotFoundError extends Error {}

// ─────────────────────────────────────────────────────────────────────────────
// 4. EXPORTS
// ─────────────────────────────────────────────────────────────────────────────

module.exports = {
  beginMarker,
  endMarker,
  renderRegion,
  extractRegion,
  replaceRegion,
  regionReproducesExactly,
  listSections,
  RegionNotFoundError,
};
